INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('889','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1462','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3101','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1479','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('114','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1078','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4292','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2673','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3745','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1694','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4701','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('417','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4416','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('578','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3922','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5079','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4707','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5301','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3363','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3544','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2077','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2612','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4203','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3454','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('899','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('556','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2383','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1412','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1112','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3987','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2305','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1262','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3537','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2986','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3289','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1661','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1918','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4370','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4012','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3875','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1492','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1819','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3472','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1286','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('664','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3927','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1853','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5075','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3414','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3815','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1540','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3338','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2510','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1443','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4769','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('405','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2882','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2024','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1589','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('950','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5502','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5149','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1856','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3655','1','11','Tláhuac','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5336','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2212','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('862','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4758','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2500','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3979','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4218','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2178','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('834','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4541','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('321','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2794','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3707','1','11','Tláhuac','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4427','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3945','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('777','1','4','Cuajimalpa de Morelos','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2720','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4013','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3705','1','11','Tláhuac','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4546','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3491','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3212','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1947','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('367','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1011','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2406','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3913','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('55','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2492','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1714','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5352','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('996','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4498','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4696','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5236','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1751','1','6','Iztacalco','','');