INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3880','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3931','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4865','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4774','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('129','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4382','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2075','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2495','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1900','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1941','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2549','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('446','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1106','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1696','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2828','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5010','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4264','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2961','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2958','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('901','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('874','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2425','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('523','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4311','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3687','1','11','Tláhuac','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2950','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5270','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2449','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2815','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2587','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1523','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4680','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('257','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3826','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4535','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1144','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('166','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('756','1','4','Cuajimalpa de Morelos','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1934','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('152','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1271','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('125','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1079','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3604','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4855','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2290','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1968','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1127','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3595','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('971','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3896','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1744','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2470','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('262','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5228','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2566','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4992','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1307','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1825','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3405','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5244','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2940','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1133','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3003','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3353','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4153','1','11','Tláhuac','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2020','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3224','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1260','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2851','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3542','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4205','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1690','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1754','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2080','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1131','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2055','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2575','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3944','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2598','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4106','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3981','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5357','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1698','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2172','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5283','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3778','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2497','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5087','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4629','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1495','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3865','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('209','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4338','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1838','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3423','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4829','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('481','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('900','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5418','1','17','Venustiano Carranza','','');