INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3156','1','9','Milpa Alta','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1293','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('980','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2785','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4794','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('146','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('124','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2585','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1565','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5328','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('119','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2089','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3154','1','9','Milpa Alta','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3073','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3785','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4058','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2349','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3010','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1902','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2388','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2542','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4628','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2807','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4408','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2645','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3947','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2513','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5308','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5088','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4959','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5342','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('724','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2210','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5103','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3556','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1952','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2239','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('112','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1922','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('484','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1013','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1008','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1614','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5026','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1274','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2965','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5154','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3063','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3241','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2257','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1792','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('993','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5304','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2918','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4238','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3000','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('813','1','4','Cuajimalpa de Morelos','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4725','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4188','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3701','1','11','Tláhuac','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1108','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1963','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4797','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5095','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2632','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4172','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1460','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3823','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('808','1','4','Cuajimalpa de Morelos','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1812','1','6','Iztacalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3830','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3926','1','12','Tlalpan','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1085','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2609','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('587','1','3','Coyoacán','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3237','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1421','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4708','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1979','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2971','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3102','1','8','La Magdalena Contreras','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4340','1','14','Benito Juárez','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('2708','1','7','Iztapalapa','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4812','1','15','Cuauhtémoc','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4240','1','13','Xochimilco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('985','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4974','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5039','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4926','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3628','1','11','Tláhuac','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3486','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('79','1','2','Azcapotzalco','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('895','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5300','1','17','Venustiano Carranza','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('3184','1','10','Álvaro Obregón','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1053','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('833','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('1185','1','5','Gustavo A. Madero','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('5118','1','16','Miguel Hidalgo','','');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador) VALUES ('4823','1','15','Cuauhtémoc','','');